export class Package {
    constructor(
        public name: string,
        public business: string,
        public address: string,
        public city: string,
        public phonenumber: string,
        public fax: string,
        public dbnumber: string,
        public maxload: string,
        public credits: string,
        public payment: string,
        public contact: string,
        public email: string,
        public billaddress: string,
        public billcity: string,
        public billphone: string,
        public billfax: string,
        public option1: boolean,
        public option2: boolean,
        public option3: boolean,
        public option4: boolean,
        public option5: boolean,
        public option6: boolean,
        public emailcheck: boolean,
        public faxcheck: boolean,
        public date: string,
        public mainname: string,
    ) {}
}
